### ISSUE TITLE
Déployer golem sur Dockerhub

### ISSUE THREAD

**Issue by Elazul** [4nth0/golem#4]
Afin de mieux intégrer golem dans la stack des différents projets, il pourrait être utile de le dockeriser et de le rendre disponible sur Dockerhub. Cela permettrait par exemple d'appeler directement l'image Docker de golem dans un docker-compose pour mocker les projets en local.

**Comment by 4nth0** [comment]
Le support de [docker a été ajouté](https://github.com/4nth0/golem/issues/4) et la publication a été faite sur [Docker Hub](https://hub.docker.com/r/4nth0/golem)
